import { generateExercises, VocabItem } from './exercise-generator';

interface Lesson { id: string; title: string; order: number; unit: string; questions: any[]; }

function v(word: string, translation: string, tr: string, ex?: string, exAr?: string): VocabItem {
  return { word, translation, transliteration: tr, ...(ex && { example: ex, exampleAr: exAr }) };
}

function buildUnit(grade: number, unitNum: number, title: string, vocab: VocabItem[]): Lesson[] {
  return Array.from({ length: 10 }, (_, i) => {
    const l = i + 1;
    const id = `en${grade}-u${unitNum}-l${l}`;
    return { id, title: l === 10 ? `Quiz: ${title}` : `${title} (${l})`, order: (unitNum - 1) * 10 + l, unit: title, questions: generateExercises(id, vocab) };
  });
}

// ━━━━━━━━━━━━━━━━━ GRADE 3 ━━━━━━━━━━━━━━━━━
const EN3: Lesson[] = [
  ...buildUnit(3,1,'Animals',[
    v('cat','قطة','kat','The cat is black.','القطة سوداء.'),
    v('dog','كلب','dog','The dog is big.','الكلب كبير.'),
    v('bird','طائر','berd','The bird flies.','الطائر يطير.'),
    v('fish','سمكة','fish','The fish swims.','السمكة تسبح.'),
    v('rabbit','أرنب','rabit'),
    v('lion','أسد','layon'),
    v('elephant','فيل','elefant'),
    v('monkey','قرد','munki'),
  ]),
  ...buildUnit(3,2,'Colors and Numbers',[
    v('red','أحمر','red','The apple is red.','التفاحة حمراء.'),
    v('blue','أزرق','blu','The sky is blue.','السماء زرقاء.'),
    v('green','أخضر','grin','The grass is green.','العشب أخضر.'),
    v('yellow','أصفر','yelow','The sun is yellow.','الشمس صفراء.'),
    v('one','واحد','wun'),
    v('two','اثنان','tu'),
    v('three','ثلاثة','thri'),
    v('ten','عشرة','ten'),
  ]),
  ...buildUnit(3,3,'Family and Greetings',[
    v('mother','أمي','mudher','My mother is kind.','أمي لطيفة.'),
    v('father','أبي','fader','My father is tall.','أبي طويل.'),
    v('sister','أخت','sister'),
    v('brother','أخ','bruder'),
    v('hello','مرحباً','helo'),
    v('goodbye','وداعاً','gudbay'),
    v('please','من فضلك','pliz'),
    v('thank you','شكراً','thengkyu'),
  ]),
  ...buildUnit(3,4,'Body Parts',[
    v('head','رأس','hed','I have a head.','عندي رأس.'),
    v('eye','عين','ay','I have two eyes.','عندي عينان.'),
    v('hand','يد','hand'),
    v('foot','قدم','fut'),
    v('nose','أنف','noz'),
    v('ear','أذن','eer'),
    v('mouth','فم','mouth'),
    v('hair','شعر','her'),
  ]),
  ...buildUnit(3,5,'School Supplies',[
    v('book','كتاب','buk','I read a book.','أنا أقرأ كتاباً.'),
    v('pen','قلم','pen','I write with a pen.','أكتب بالقلم.'),
    v('pencil','قلم رصاص','pensil'),
    v('bag','حقيبة','bag'),
    v('ruler','مسطرة','ruler'),
    v('eraser','ممحاة','irazer'),
    v('notebook','كراس','notbuk'),
    v('desk','مكتب / طاولة','desk'),
  ]),
  ...buildUnit(3,6,'Food',[
    v('apple','تفاحة','apel','I eat an apple.','أنا آكل تفاحة.'),
    v('bread','خبز','bred','I like bread.','أحب الخبز.'),
    v('milk','حليب','milk'),
    v('water','ماء','woter'),
    v('egg','بيضة','eg'),
    v('rice','أرز','rays'),
    v('banana','موزة','banana'),
    v('orange','برتقالة','orenj'),
  ]),
  ...buildUnit(3,7,'Daily Routine',[
    v('wake up','يصحو / يستيقظ','weyk up','I wake up at 7.','أصحو في الساعة 7.'),
    v('eat','يأكل','it','I eat breakfast.','أتناول الفطور.'),
    v('go to school','يذهب للمدرسة','go tu skul'),
    v('study','يدرس','studi'),
    v('play','يلعب','play'),
    v('sleep','ينام','slip'),
    v('read','يقرأ','rid'),
    v('write','يكتب','rayt'),
  ]),
  ...buildUnit(3,8,'Pre-Foundation Test',[
    v('cat','قطة','kat'),
    v('red','أحمر','red'),
    v('mother','أمي','mudher'),
    v('book','كتاب','buk'),
    v('apple','تفاحة','apel'),
    v('hello','مرحباً','helo'),
    v('hand','يد','hand'),
    v('sleep','ينام','slip'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 4 ━━━━━━━━━━━━━━━━━
const EN4: Lesson[] = [
  ...buildUnit(4,1,'Present Simple',[
    v('run','يركض','run','He runs every day.','هو يركض كل يوم.'),
    v('jump','يقفز','jump','She jumps high.','هي تقفز عالياً.'),
    v('swim','يسبح','swim','They swim in the pool.','هم يسبحون في المسبح.'),
    v('fly','يطير','flay','Birds fly in the sky.','الطيور تطير في السماء.'),
    v('sing','يغني','sing'),
    v('dance','يرقص','dans'),
    v('draw','يرسم','draw'),
    v('paint','يرسم بالألوان','paynt'),
  ]),
  ...buildUnit(4,2,'To Be + Questions',[
    v('am','أكون / أنا','am','I am a student.','أنا طالب.'),
    v('is','يكون / هو-هي','iz','She is happy.','هي سعيدة.'),
    v('are','يكونون / أنتم','ar','They are friends.','هم أصدقاء.'),
    v('who','من','hu','Who is he?','من هو؟'),
    v('what','ماذا','wot','What is this?','ما هذا؟'),
    v('where','أين','wer','Where are you?','أين أنت؟'),
    v('when','متى','wen','When is the test?','متى الاختبار؟'),
    v('why','لماذا','way','Why are you here?','لماذا أنت هنا؟'),
  ]),
  ...buildUnit(4,3,'Daily Routine Vocabulary',[
    v('morning','صباح','morning','Good morning!','صباح الخير!'),
    v('afternoon','بعد الظهر','afternoon'),
    v('evening','مساء','evening','Good evening!','مساء الخير!'),
    v('night','ليل','nayt'),
    v('always','دائماً','olwez'),
    v('sometimes','أحياناً','samtaymz'),
    v('never','أبداً','never'),
    v('every day','كل يوم','evri day'),
  ]),
  ...buildUnit(4,4,'Hobbies and Sports',[
    v('football','كرة القدم','futbol','I like football.','أحب كرة القدم.'),
    v('basketball','كرة السلة','basketbol'),
    v('reading','القراءة','reding'),
    v('cooking','الطبخ','kuking'),
    v('painting','الرسم','paynting'),
    v('cycling','ركوب الدراجة','saykling'),
    v('swimming','السباحة','swiming'),
    v('running','الجري','runing'),
  ]),
  ...buildUnit(4,5,'Adjectives',[
    v('big','كبير','big','The house is big.','البيت كبير.'),
    v('small','صغير','smol'),
    v('tall','طويل','tol'),
    v('short','قصير','short'),
    v('fast','سريع','fast'),
    v('slow','بطيء','slow'),
    v('happy','سعيد','happi','I am happy.','أنا سعيد.'),
    v('sad','حزين','sad'),
  ]),
  ...buildUnit(4,6,'Foundation Vocabulary',[
    v('house','بيت','haws','My house is big.','بيتي كبير.'),
    v('school','مدرسة','skul','I go to school.','أذهب للمدرسة.'),
    v('friend','صديق','frend','He is my friend.','هو صديقي.'),
    v('teacher','معلم','ticher'),
    v('city','مدينة','siti'),
    v('road','طريق','rod'),
    v('park','حديقة عامة','park'),
    v('shop','متجر','shop'),
  ]),
  ...buildUnit(4,7,'Numbers and Time',[
    v('eleven','أحد عشر','eleven'),
    v('twenty','عشرون','twenti'),
    v('fifty','خمسون','fifti'),
    v('hundred','مئة','hundred'),
    v('hour','ساعة','awer'),
    v('minute','دقيقة','minit'),
    v('week','أسبوع','wik'),
    v('month','شهر','munth'),
  ]),
  ...buildUnit(4,8,'Test — Grade 4',[
    v('run','يركض','run'),
    v('happy','سعيد','happi'),
    v('morning','صباح','morning'),
    v('football','كرة القدم','futbol'),
    v('house','بيت','haws'),
    v('twenty','عشرون','twenti'),
    v('always','دائماً','olwez'),
    v('friend','صديق','frend'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 5 ━━━━━━━━━━━━━━━━━
const EN5: Lesson[] = [
  ...buildUnit(5,1,'Present Continuous',[
    v('running','يركض الآن','runing','He is running now.','هو يركض الآن.'),
    v('eating','يأكل الآن','iting','She is eating lunch.','هي تأكل الغداء.'),
    v('reading','يقرأ الآن','reding'),
    v('writing','يكتب الآن','rayting'),
    v('playing','يلعب الآن','playing'),
    v('sleeping','ينام الآن','sliping'),
    v('watching','يشاهد الآن','woching'),
    v('working','يعمل الآن','wurking'),
  ]),
  ...buildUnit(5,2,'Past Simple Regular',[
    v('walked','مشى / ذهب','wokt','He walked to school.','هو مشى إلى المدرسة.'),
    v('talked','تكلم','tokt'),
    v('played','لعب','playd'),
    v('watched','شاهد','wochtd'),
    v('cooked','طبخ','kukt'),
    v('cleaned','نظّف','klind'),
    v('helped','ساعد','helpt'),
    v('visited','زار','vizitid'),
  ]),
  ...buildUnit(5,3,'A2 Vocabulary',[
    v('important','مهم','important','This is important.','هذا مهم.'),
    v('interesting','ممتع','intresting'),
    v('difficult','صعب','difikult'),
    v('easy','سهل','izy'),
    v('beautiful','جميل','byutiful'),
    v('dangerous','خطير','denjrus'),
    v('healthy','صحي','helthy'),
    v('delicious','لذيذ','dilishus'),
  ]),
  ...buildUnit(5,4,'Writing a Paragraph',[
    v('paragraph','فقرة','paragraf','Write a paragraph.','اكتب فقرة.'),
    v('topic','موضوع','topik'),
    v('sentence','جملة','sentens'),
    v('idea','فكرة','aydia'),
    v('example','مثال','egzampel'),
    v('conclusion','خاتمة / استنتاج','konkluzhen'),
    v('introduction','مقدمة','introdukshon'),
    v('detail','تفصيل','ditayl'),
  ]),
  ...buildUnit(5,5,'Listening Vocabulary',[
    v('listen','يستمع','lisen','Listen carefully!','استمع بانتباه!'),
    v('understand','يفهم','understend'),
    v('repeat','يكرر','ripit'),
    v('question','سؤال','kweschn'),
    v('answer','جواب','enser'),
    v('correct','صحيح','korekt'),
    v('wrong','خاطئ','rong'),
    v('try again','حاول مرة أخرى','tray agen'),
  ]),
  ...buildUnit(5,6,'Speak — Introduce Yourself',[
    v('name','اسم','naym','My name is...','اسمي...'),
    v('age','عمر','ayj','I am 10 years old.','عمري 10 سنوات.'),
    v('live','يسكن','liv','I live in...','أسكن في...'),
    v('like','يحب','layk','I like football.','أحب كرة القدم.'),
    v('hobby','هواية','hobi'),
    v('favorite','المفضل','feyvorit'),
    v('country','بلد / دولة','kuntri'),
    v('language','لغة','langwij'),
  ]),
  ...buildUnit(5,7,'Foundation Vocabulary A2',[
    v('market','سوق','market'),
    v('hospital','مستشفى','hospital'),
    v('library','مكتبة','laybrary'),
    v('station','محطة','stayshon'),
    v('airport','مطار','airport'),
    v('restaurant','مطعم','restront'),
    v('bank','بنك','bank'),
    v('pharmacy','صيدلية','farmasi'),
  ]),
  ...buildUnit(5,8,'Meitzav Test',[
    v('running','يركض الآن','runing'),
    v('walked','مشى','wokt'),
    v('important','مهم','important'),
    v('paragraph','فقرة','paragraf'),
    v('listen','يستمع','lisen'),
    v('name','اسم','naym'),
    v('market','سوق','market'),
    v('difficult','صعب','difikult'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 6 ━━━━━━━━━━━━━━━━━
const EN6: Lesson[] = [
  ...buildUnit(6,1,'Past Simple Irregular',[
    v('went','ذهب (ماضٍ شاذ)','went','He went to the store.','هو ذهب إلى المتجر.'),
    v('ate','أكل (ماضٍ شاذ)','eyt'),
    v('wrote','كتب (ماضٍ شاذ)','rot'),
    v('read','قرأ (ماضٍ شاذ)','red'),
    v('saw','رأى (ماضٍ شاذ)','so'),
    v('came','أتى (ماضٍ شاذ)','kaym'),
    v('ran','ركض (ماضٍ شاذ)','ran'),
    v('spoke','تكلم (ماضٍ شاذ)','spok'),
  ]),
  ...buildUnit(6,2,'Future: Will and Going To',[
    v('will go','سيذهب (will)','wil go','I will go tomorrow.','سأذهب غداً.'),
    v('will eat','سيأكل (will)','wil it'),
    v('going to','سيفعل (going to)','going tu','I am going to study.','سأدرس.'),
    v('tomorrow','غداً','tumorow'),
    v('next week','الأسبوع القادم','nekst wik'),
    v('soon','قريباً','sun'),
    v('later','لاحقاً','laytr'),
    v('future','المستقبل','fyuchur'),
  ]),
  ...buildUnit(6,3,'Comparative and Superlative',[
    v('bigger','أكبر','bigr','My house is bigger.','بيتي أكبر.'),
    v('smaller','أصغر','smolr'),
    v('taller','أطول','tolr'),
    v('faster','أسرع','fastr'),
    v('the biggest','الأكبر','the biggest'),
    v('the best','الأفضل','the best'),
    v('the worst','الأسوأ','the worst'),
    v('than','من (مقارنة)','den','She is taller than me.','هي أطول مني.'),
  ]),
  ...buildUnit(6,4,'Writing a Letter',[
    v('dear','عزيزي','deer','Dear friend,','عزيزي الصديق،'),
    v('yours sincerely','مع تحياتي','yorz sinserli'),
    v('letter','رسالة','letr'),
    v('write','يكتب','rayt'),
    v('address','عنوان','adres'),
    v('date','تاريخ','dayt'),
    v('paragraph','فقرة','paragraf'),
    v('signature','توقيع','signitchur'),
  ]),
  ...buildUnit(6,5,'Reading Longer Texts',[
    v('text','نص','tekst','Read the text carefully.','اقرأ النص بعناية.'),
    v('story','قصة','stori'),
    v('character','شخصية','kariktr'),
    v('setting','الزمان والمكان','seting'),
    v('plot','حبكة','plot'),
    v('theme','موضوع / فكرة','thim'),
    v('author','مؤلف','othr'),
    v('reader','قارئ','ridr'),
  ]),
  ...buildUnit(6,6,'A2 Vocabulary 400 words',[
    v('environment','بيئة','environment'),
    v('technology','تكنولوجيا','teknoloji'),
    v('education','تعليم','edyukayshon'),
    v('culture','ثقافة','kulchur'),
    v('tradition','تقليد','tradishon'),
    v('community','مجتمع','komuniti'),
    v('government','حكومة','guvermnt'),
    v('economy','اقتصاد','ekonomi'),
  ]),
  ...buildUnit(6,7,'Dialogue',[
    v('agree','يوافق','agri','I agree with you.','أوافقك الرأي.'),
    v('disagree','يختلف','disagri'),
    v('suggest','يقترح','sujest'),
    v('ask','يسأل','ask'),
    v('answer','يجيب','enser'),
    v('explain','يشرح','eksplayn'),
    v('describe','يصف','diskrayb'),
    v('discuss','يناقش','diskus'),
  ]),
  ...buildUnit(6,8,'Test — Grade 6',[
    v('went','ذهب','went'),
    v('will go','سيذهب','wil go'),
    v('bigger','أكبر','bigr'),
    v('dear','عزيزي','deer'),
    v('story','قصة','stori'),
    v('environment','بيئة','environment'),
    v('agree','يوافق','agri'),
    v('author','مؤلف','othr'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 7 ━━━━━━━━━━━━━━━━━
const EN7: Lesson[] = [
  ...buildUnit(7,1,'Present Perfect',[
    v('have been','كنت / ذهبت (قد)','hav bin','I have been to London.','لقد ذهبت إلى لندن.'),
    v('have seen','رأيت (قد)','hav sin'),
    v('have eaten','أكلت (قد)','hav itn'),
    v('have never','لم أفعل قط','hav nevr'),
    v('have already','فعلت بالفعل','hav olredi'),
    v('have just','فعلت للتو','hav just'),
    v('experience','تجربة','ekspiriens'),
    v('since','منذ','sins','I have lived here since 2010.','عشت هنا منذ 2010.'),
  ]),
  ...buildUnit(7,2,'First Conditional',[
    v('if','إذا','if','If it rains, I will stay.','إذا مطرت، سأبقى.'),
    v('will','سـ / سوف','wil'),
    v('might','ربما','mayt'),
    v('condition','شرط','kondishon'),
    v('result','نتيجة','rizult'),
    v('unless','إلا إذا','unles'),
    v('provided that','بشرط أن','provided dat'),
    v('as long as','طالما','az long az'),
  ]),
  ...buildUnit(7,3,'B1 Vocabulary',[
    v('opportunity','فرصة','oportuniti'),
    v('challenge','تحدٍّ','chalinjh'),
    v('achievement','إنجاز','achivmnt'),
    v('responsibility','مسؤولية','risponsibiliti'),
    v('relationship','علاقة','rilayshonship'),
    v('environment','بيئة','invayrenmnt'),
    v('society','مجتمع','sosayiti'),
    v('progress','تقدم','progres'),
  ]),
  ...buildUnit(7,4,'Writing a Formal Letter',[
    v('formal','رسمي','formal','Write a formal letter.','اكتب رسالة رسمية.'),
    v('informal','غير رسمي','informal'),
    v('recipient','المستلم','resipient'),
    v('purpose','الهدف','purpos'),
    v('opening','الافتتاحية','opning'),
    v('closing','الختام','klozing'),
    v('polite','مؤدب','polayt'),
    v('professional','احترافي','profeshonal'),
  ]),
  ...buildUnit(7,5,'Reading News Texts',[
    v('headline','عنوان رئيسي','hedlayn','Read the headline.','اقرأ العنوان.'),
    v('article','مقالة','artikl'),
    v('journalist','صحفي','jurnalist'),
    v('report','تقرير','riport'),
    v('fact','حقيقة','fakt'),
    v('opinion','رأي','opinyen'),
    v('source','مصدر','sors'),
    v('evidence','دليل','evidens'),
  ]),
  ...buildUnit(7,6,'Listening B1',[
    v('accent','لكنة / نطق','aksent'),
    v('fluent','طليق','fluent'),
    v('native speaker','ناطق أصلي','nativ spikr'),
    v('comprehend','يفهم بعمق','komprehend'),
    v('infer','يستنتج','infr'),
    v('main idea','الفكرة الرئيسية','mayn aydia'),
    v('supporting detail','تفصيل داعم','suporting ditayl'),
    v('paraphrase','يعيد الصياغة','parafrayz'),
  ]),
  ...buildUnit(7,7,'Speaking Extended',[
    v('present','يقدم / يعرض','prezent','I will present my project.','سأقدم مشروعي.'),
    v('argue','يتجادل','argyu'),
    v('express','يعبّر','ekspres'),
    v('opinion','رأي','opinyen'),
    v('convince','يقنع','konvins'),
    v('debate','نقاش','dibat'),
    v('point of view','وجهة نظر','poynt ov vyu'),
    v('evidence','دليل','evidens'),
  ]),
  ...buildUnit(7,8,'Test — Grade 7',[
    v('have been','كنت','hav bin'),
    v('if','إذا','if'),
    v('opportunity','فرصة','oportuniti'),
    v('formal','رسمي','formal'),
    v('headline','عنوان رئيسي','hedlayn'),
    v('fluent','طليق','fluent'),
    v('present','يقدم','prezent'),
    v('evidence','دليل','evidens'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 8 ━━━━━━━━━━━━━━━━━
const EN8: Lesson[] = [
  ...buildUnit(8,1,'Passive Voice',[
    v('is written','يُكتب','iz ritn','The book is written by him.','الكتاب يُكتب منه.'),
    v('was built','بُني','woz bilt'),
    v('is made','يُصنع','iz mayd'),
    v('was sent','أُرسل','woz sent'),
    v('is spoken','يُتحدث به','iz spokn'),
    v('was found','وُجد','woz fawnd'),
    v('is used','يُستخدم','iz yuzd'),
    v('was written','كُتب','woz ritn'),
  ]),
  ...buildUnit(8,2,'Modal Verbs',[
    v('can','يستطيع','kan','I can swim.','أستطيع السباحة.'),
    v('could','كان يستطيع','kud'),
    v('must','يجب','must','You must study.','يجب أن تدرس.'),
    v('should','ينبغي','shud'),
    v('may','يجوز / ربما','may'),
    v('might','ربما','mayt'),
    v('would','سيكون / كان سيفعل','wud'),
    v('shall','سوف','shal'),
  ]),
  ...buildUnit(8,3,'Academic Reading',[
    v('thesis','أطروحة / فكرة رئيسية','thesis'),
    v('argument','حجة','argument'),
    v('evidence','دليل','evidens'),
    v('conclusion','استنتاج','konkluzhen'),
    v('analyze','يحلل','analayz'),
    v('evaluate','يقيّم','evalyuat'),
    v('compare','يقارن','komper'),
    v('contrast','يوضح الاختلاف','kontrast'),
  ]),
  ...buildUnit(8,4,'Essay Writing',[
    v('introduction','مقدمة','introdukshon','Write an introduction.','اكتب مقدمة.'),
    v('body paragraph','فقرة المتن','bodi paragraf'),
    v('topic sentence','جملة الموضوع','topik sentens'),
    v('supporting sentence','جملة داعمة','suporting sentens'),
    v('transition','انتقال','tranzishon'),
    v('conclusion','خاتمة','konkluzhen'),
    v('coherence','تماسك','koherens'),
    v('argument','حجة','argument'),
  ]),
  ...buildUnit(8,5,'CEFR B1 Skills',[
    v('B1 level','مستوى B1','bi-wun level'),
    v('independent','مستقل','independent'),
    v('interact','يتفاعل','interakt'),
    v('produce','ينتج / يؤلف','prodius'),
    v('cope','يتعامل مع','kop'),
    v('familiar','مألوف','familier'),
    v('unfamiliar','غير مألوف','unfamilier'),
    v('situation','موقف','situayshon'),
  ]),
  ...buildUnit(8,6,'Listening Detailed',[
    v('speaker','متحدث','spikr'),
    v('tone','نبرة','ton'),
    v('attitude','موقف / اتجاه','atitiud'),
    v('imply','يوحي / يُضمر','implay'),
    v('explicit','صريح','eksplisit'),
    v('implicit','ضمني','implisit'),
    v('gist','الجوهر / الفكرة العامة','jist'),
    v('detail','تفصيل','ditayl'),
  ]),
  ...buildUnit(8,7,'Meitzav Preparation',[
    v('reading comprehension','فهم مقروء','reding komprihenzhon'),
    v('writing task','مهمة الكتابة','rayting task'),
    v('listening task','مهمة الاستماع','lisening task'),
    v('vocabulary','مفردات','vokabyleri'),
    v('grammar','قواعد','gramer'),
    v('score','درجة','skor'),
    v('achieve','يحقق','achiv'),
    v('succeed','ينجح','suksid'),
  ]),
  ...buildUnit(8,8,'Meitzav Test',[
    v('is written','يُكتب','iz ritn'),
    v('must','يجب','must'),
    v('thesis','أطروحة','thesis'),
    v('introduction','مقدمة','introdukshon'),
    v('B1 level','مستوى B1','bi-wun level'),
    v('gist','الجوهر','jist'),
    v('succeed','ينجح','suksid'),
    v('evidence','دليل','evidens'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 9 ━━━━━━━━━━━━━━━━━
const EN9: Lesson[] = [
  ...buildUnit(9,1,'Reported Speech',[
    v('said','قال','sed','She said she was tired.','هي قالت إنها متعبة.'),
    v('told','أخبر','told'),
    v('asked','سأل','askt'),
    v('reported','أفاد / أبلغ','riportid'),
    v('stated','أعلن / صرّح','staytid'),
    v('claimed','ادّعى','klaymd'),
    v('admitted','اعترف','admitid'),
    v('denied','أنكر','dinayed'),
  ]),
  ...buildUnit(9,2,'2nd and 3rd Conditional',[
    v('if I were','لو كنت','if ay wer','If I were rich, I would travel.','لو كنت غنياً، لسافرت.'),
    v('would have','كان سيفعل (لو)','wud hav'),
    v('had studied','لو كان قد درس','had studied'),
    v('could have','كان يستطيع (لو)','kud hav'),
    v('unreal','غير واقعي','unreel'),
    v('hypothetical','افتراضي','haypothetikl'),
    v('regret','ندم','rigret'),
    v('imaginary','خيالي','imajineri'),
  ]),
  ...buildUnit(9,3,'B1 Academic Vocabulary',[
    v('analyze','يحلل','analayz'),
    v('evaluate','يقيّم','evalyuat'),
    v('interpret','يفسّر','intrprit'),
    v('synthesize','يركّب / يجمع','sinthasayz'),
    v('justify','يبرر','justifay'),
    v('identify','يحدد / يتعرف','aydentifay'),
    v('demonstrate','يُثبت / يوضح','demonstrayt'),
    v('illustrate','يوضح بمثال','ilustrayt'),
  ]),
  ...buildUnit(9,4,'Academic Writing',[
    v('abstract','ملخص / مستخلص','abstrakt'),
    v('bibliography','قائمة مراجع','bibliografi'),
    v('citation','استشهاد / اقتباس','sitayshon'),
    v('hypothesis','فرضية','haypothisis'),
    v('methodology','منهجية','methedoloji'),
    v('research','بحث','risrch'),
    v('findings','نتائج','fayndingz'),
    v('recommendation','توصية','rekomendayshon'),
  ]),
  ...buildUnit(9,5,'Critical Reading',[
    v('bias','تحيز','bayis'),
    v('perspective','منظور','perspektiv'),
    v('assumption','افتراض','asumshon'),
    v('inference','استنتاج','inferens'),
    v('implication','تضمين / نتيجة ضمنية','implikayshon'),
    v('validity','صحة / صلاحية','validiti'),
    v('credibility','مصداقية','kredibiliti'),
    v('reliability','موثوقية','rilayabiliti'),
  ]),
  ...buildUnit(9,6,'Listening B1+',[
    v('nuance','دقة / فروق دقيقة','nyuens'),
    v('emphasis','تأكيد / تشديد','emfasis'),
    v('register','مستوى اللغة','rejistre'),
    v('formal register','مستوى رسمي','formal rejistre'),
    v('informal register','مستوى غير رسمي','informal rejistre'),
    v('coherent','متماسك','kohirent'),
    v('logical','منطقي','lojikl'),
    v('structured','منظم','struktchrd'),
  ]),
  ...buildUnit(9,7,'High School Prep',[
    v('bagrut','بجروت (امتحان)','bagrut'),
    v('module','وحدة / موديول','modul'),
    v('oral exam','امتحان شفوي','oral egzam'),
    v('written exam','امتحان كتابي','ritn egzam'),
    v('project','مشروع','projekt'),
    v('portfolio','ملف إنجازات','portfolio'),
    v('presentation','عرض تقديمي','prezentayshon'),
    v('pass','ينجح','pas'),
  ]),
  ...buildUnit(9,8,'Asif Test',[
    v('said','قال','sed'),
    v('if I were','لو كنت','if ay wer'),
    v('analyze','يحلل','analayz'),
    v('research','بحث','risrch'),
    v('bias','تحيز','bayis'),
    v('nuance','دقة','nyuens'),
    v('bagrut','بجروت','bagrut'),
    v('portfolio','ملف إنجازات','portfolio'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 10 ━━━━━━━━━━━━━━━━━
const EN10: Lesson[] = [
  ...buildUnit(10,1,'Module A — Reading',[
    v('comprehension','فهم مقروء','komprihenzhon','Reading comprehension test.','اختبار فهم مقروء.'),
    v('inference','استنتاج','inferens'),
    v('main idea','الفكرة الرئيسية','mayn aydia'),
    v('supporting detail','تفصيل داعم','suporting ditayl'),
    v('tone','نبرة','ton'),
    v('mood','مزاج / جو','mud'),
    v('figurative language','لغة مجازية','figyurativ langwij'),
    v('literal meaning','المعنى الحرفي','literal mining'),
  ]),
  ...buildUnit(10,2,'Module B — Writing',[
    v('essay','مقال','esey','Write an essay.','اكتب مقالاً.'),
    v('narrative','سرد','narativ'),
    v('descriptive','وصفي','diskriptiv'),
    v('argumentative','حجاجي','argumentativ'),
    v('expository','تفسيري','ekspositori'),
    v('draft','مسودة','draft'),
    v('revise','يراجع','rivayz'),
    v('edit','يعدّل','edit'),
  ]),
  ...buildUnit(10,3,'Module C — Listening',[
    v('interview','مقابلة','intervyu'),
    v('podcast','بودكاست','podkast'),
    v('dialogue','حوار','dayalog'),
    v('monologue','مونولوج','monolog'),
    v('transcript','نص مكتوب','transkript'),
    v('summarize','يلخص','sumarayz'),
    v('key point','نقطة رئيسية','ki poynt'),
    v('speaker\'s purpose','غرض المتحدث','spikrz purpos'),
  ]),
  ...buildUnit(10,4,'Bagrut 3 Points',[
    v('short answer','جواب قصير','short enser'),
    v('multiple choice','اختيار من متعدد','multipel choys'),
    v('open question','سؤال مفتوح','open kweschn'),
    v('text type','نوع النص','tekst tayp'),
    v('register','مستوى اللغة','rejistre'),
    v('purpose','الغرض','purpos'),
    v('audience','الجمهور المستهدف','odiens'),
    v('structure','البنية','strukchur'),
  ]),
  ...buildUnit(10,5,'Bagrut 5 Points',[
    v('literary analysis','تحليل أدبي','litareri analis'),
    v('theme','موضوع / فكرة كبرى','thim'),
    v('symbol','رمز','simbl'),
    v('irony','إيرونية / سخرية','ayerni'),
    v('characterization','رسم الشخصية','karakterizayshon'),
    v('setting','الزمان والمكان','seting'),
    v('narrator','راوٍ','nerater'),
    v('point of view','وجهة نظر','poynt ov vyu'),
  ]),
  ...buildUnit(10,6,'COBE Introduction',[
    v('COBE','كوبي — اختبار الكفاءة','kobi'),
    v('competency','كفاءة','kompetensis'),
    v('task','مهمة','task'),
    v('scenario','سيناريو','sinaryo'),
    v('role play','تمثيل أدوار','rol play'),
    v('evaluate','يقيّم','evalyuat'),
    v('criteria','معايير','krayteria'),
    v('performance','أداء','performens'),
  ]),
  ...buildUnit(10,7,'Vocabulary B1+/B2',[
    v('sophisticated','متطور / راقٍ','sofistikated'),
    v('coherent','متماسك','kohirent'),
    v('precise','دقيق','prisays'),
    v('elaborate','مفصّل / متقن','elaborayt'),
    v('nuanced','دقيق / ذو فروق دقيقة','nyuenst'),
    v('concise','موجز / مختصر','konsays'),
    v('articulate','يعبّر بوضوح','artikyulayt'),
    v('eloquent','بليغ / فصيح','elokwent'),
  ]),
  ...buildUnit(10,8,'Bagrut Mock',[
    v('comprehension','فهم مقروء','komprihenzhon'),
    v('essay','مقال','esey'),
    v('interview','مقابلة','intervyu'),
    v('literary analysis','تحليل أدبي','litareri analis'),
    v('COBE','اختبار الكفاءة','kobi'),
    v('sophisticated','راقٍ','sofistikated'),
    v('narrator','راوٍ','nerater'),
    v('performance','أداء','performens'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 11 ━━━━━━━━━━━━━━━━━
const EN11: Lesson[] = [
  ...buildUnit(11,1,'B2 Reading Skills',[
    v('subtext','ما تحت النص','subtekst'),
    v('connotation','دلالة ضمنية','konotayshon'),
    v('denotation','المعنى الحرفي','denotayshon'),
    v('allusion','إشارة / تلميح','aluzhon'),
    v('ambiguity','غموض / التباس','ambigyuti'),
    v('paradox','مفارقة','paradoks'),
    v('foreshadowing','استباق الأحداث','forshadowing'),
    v('flashback','استرجاع','flashbak'),
  ]),
  ...buildUnit(11,2,'Advanced Writing',[
    v('rhetoric','بلاغة','retorik'),
    v('persuasion','إقناع','prsuazhon'),
    v('rhetorical question','سؤال بلاغي','retorikal kweschn'),
    v('anecdote','حكاية قصيرة','anekdot'),
    v('analogy','تشابه / مماثلة','analoji'),
    v('counterargument','حجة مضادة','kawntir argument'),
    v('refutation','دحض','refyutayshon'),
    v('concession','تسليم / اعتراف','konseshon'),
  ]),
  ...buildUnit(11,3,'COBE Full Preparation',[
    v('simulate','يحاكي','simyulayt'),
    v('authentic','أصيل / حقيقي','otentik'),
    v('task-based','قائم على المهام','task-bayst'),
    v('oral presentation','عرض شفوي','oral prezentayshon'),
    v('portfolio entry','مدخل ملف الإنجاز','portfolio entri'),
    v('self-evaluation','التقييم الذاتي','self-evalyuayshon'),
    v('peer evaluation','تقييم الأقران','peer evalyuayshon'),
    v('achievement','إنجاز','achivmnt'),
  ]),
  ...buildUnit(11,4,'Projects and Interviews',[
    v('project proposal','مقترح مشروع','projekt prpozl'),
    v('research paper','ورقة بحثية','risrch paypr'),
    v('interview question','سؤال المقابلة','intervyu kweschn'),
    v('respond','يرد / يجيب','rispond'),
    v('elaborate','يفصّل','elaborayt'),
    v('justify','يبرر','justifay'),
    v('reflect','يتأمل','riflekt'),
    v('feedback','تغذية راجعة','fidbak'),
  ]),
  ...buildUnit(11,5,'All Modules A+B+C',[
    v('module A reading','وحدة القراءة','modul A reding'),
    v('module B writing','وحدة الكتابة','modul B rayting'),
    v('module C listening','وحدة الاستماع','modul C lisening'),
    v('oral component','المكوّن الشفوي','oral komponent'),
    v('written component','المكوّن الكتابي','ritn komponent'),
    v('time management','إدارة الوقت','taym manijmnt'),
    v('exam strategy','استراتيجية الامتحان','egzam stratiiji'),
    v('accuracy','دقة','akyrasi'),
  ]),
  ...buildUnit(11,6,'Bagrut Papers 2019-2024',[
    v('past paper','ورقة امتحان سابقة','past paypr'),
    v('marking scheme','مخطط التصحيح','marking skim'),
    v('model answer','جواب نموذجي','model enser'),
    v('grade boundary','حد النجاح','grayd bawndri'),
    v('partial credit','درجة جزئية','parshal kredit'),
    v('full marks','الدرجة الكاملة','ful marks'),
    v('time pressure','ضغط الوقت','taym preshr'),
    v('exam technique','تقنية الامتحان','egzam teknik'),
  ]),
  ...buildUnit(11,7,'Speaking Advanced',[
    v('fluency','طلاقة','fluensi'),
    v('accuracy','دقة','akyrasi'),
    v('pronunciation','نطق','pronunsiyayshon'),
    v('intonation','تنغيم','intonayshon'),
    v('stress','التشديد / الضغط','stres'),
    v('natural speech','كلام طبيعي','nachurl spich'),
    v('spontaneous','تلقائي','spontaniyus'),
    v('elaborate','يفصّل ويوضح','elaborayt'),
  ]),
  ...buildUnit(11,8,'Bagrut Mock Full',[
    v('subtext','ما تحت النص','subtekst'),
    v('rhetoric','بلاغة','retorik'),
    v('simulate','يحاكي','simyulayt'),
    v('project proposal','مقترح مشروع','projekt prpozl'),
    v('module A reading','وحدة القراءة','modul A reding'),
    v('past paper','ورقة امتحان سابقة','past paypr'),
    v('fluency','طلاقة','fluensi'),
    v('exam technique','تقنية الامتحان','egzam teknik'),
  ]),
];

// ━━━━━━━━━━━━━━━━━ GRADE 12 ━━━━━━━━━━━━━━━━━
const EN12: Lesson[] = [
  ...buildUnit(12,1,'Complete Review',[
    v('present simple','المضارع البسيط','preznt simpel'),
    v('past simple','الماضي البسيط','past simpel'),
    v('present perfect','المضارع التام','preznt perfekt'),
    v('passive voice','المجهول','pasiv voys'),
    v('conditional','الشرطي','kondishonl'),
    v('reported speech','الكلام المنقول','riportid spich'),
    v('modal verbs','أفعال الصيغة','modl verbz'),
    v('vocabulary','مفردات','vokabyleri'),
  ]),
  ...buildUnit(12,2,'Bagrut Papers 2014-2024',[
    v('comprehension question','سؤال فهم مقروء','komprihenzhon kweschn'),
    v('literary text','نص أدبي','litareri tekst'),
    v('non-literary text','نص غير أدبي','non-litareri tekst'),
    v('written task','مهمة كتابية','ritn task'),
    v('oral task','مهمة شفوية','oral task'),
    v('scoring rubric','جدول التقييم','skoring rubrik'),
    v('word limit','حد الكلمات','wrd limit'),
    v('time allocation','توزيع الوقت','taym alokayshon'),
  ]),
  ...buildUnit(12,3,'COBE Final Practice',[
    v('final assessment','التقييم النهائي','faynel asesmnt'),
    v('competency-based','قائم على الكفاءة','kompetensibased'),
    v('life skills','مهارات الحياة','layf skilz'),
    v('critical thinking','التفكير النقدي','kritikel thingking'),
    v('problem-solving','حل المشكلات','problem-solving'),
    v('communication','تواصل','komyunikayshon'),
    v('teamwork','العمل الجماعي','timwrk'),
    v('creativity','إبداع','kriativiti'),
  ]),
  ...buildUnit(12,4,'3 Points Final Exam',[
    v('basic comprehension','فهم مقروء أساسي','baysiك komprihenzhon'),
    v('simple essay','مقال بسيط','simpel esey'),
    v('short answer','جواب قصير','short enser'),
    v('vocabulary in context','مفردات في السياق','vokabyleri in kontekst'),
    v('spelling','الإملاء','speling'),
    v('grammar in use','القواعد التطبيقية','gramer in yuz'),
    v('functional language','لغة وظيفية','funkshonl langwij'),
    v('common phrases','عبارات شائعة','komon frayziz'),
  ]),
  ...buildUnit(12,5,'5 Points Final Exam',[
    v('literary analysis','تحليل أدبي','litareri analis'),
    v('argumentative essay','مقال حجاجي','argumentativ esey'),
    v('complex grammar','قواعد معقدة','kompleks gramer'),
    v('advanced vocabulary','مفردات متقدمة','advancst vokabyleri'),
    v('critical analysis','تحليل نقدي','kritikel analis'),
    v('textual evidence','دليل نصي','tekstyul evidens'),
    v('coherent argument','حجة متماسكة','kohirent argument'),
    v('sophisticated style','أسلوب راقٍ','sofistikated stayl'),
  ]),
  ...buildUnit(12,6,'Exam Techniques',[
    v('time management','إدارة الوقت','taym manijmnt'),
    v('read the question','اقرأ السؤال','rid the kweschn'),
    v('plan your answer','خطط لجوابك','plan yor enser'),
    v('check your work','راجع عملك','chek yor wrk'),
    v('avoid repetition','تجنب التكرار','avoed repetishon'),
    v('vary vocabulary','نوّع المفردات','very vokabyleri'),
    v('stay on topic','ابق في الموضوع','stay on topik'),
    v('clear handwriting','خط واضح','kleer handrayting'),
  ]),
  ...buildUnit(12,7,'Project Presentations',[
    v('title','عنوان','taytel'),
    v('introduction','مقدمة','introdukshon'),
    v('main points','النقاط الرئيسية','mayn poynts'),
    v('evidence','دليل','evidens'),
    v('visual aid','مساعدة بصرية','vizhul ayd'),
    v('conclusion','خاتمة','konkluzhen'),
    v('question and answer','أسئلة وأجوبة','kweschn and enser'),
    v('confident delivery','أداء بثقة','konfident diliveri'),
  ]),
  ...buildUnit(12,8,'Bagrut Final',[
    v('comprehension','فهم','komprihenzhon'),
    v('essay','مقال','esey'),
    v('literary analysis','تحليل أدبي','litareri analis'),
    v('oral exam','شفوي','oral egzam'),
    v('COBE','كوبي','kobi'),
    v('critical thinking','تفكير نقدي','kritikel thingking'),
    v('time management','إدارة الوقت','taym manijmnt'),
    v('success','نجاح','suksess'),
  ]),
];

export const ENGLISH_BY_GRADE: Record<number, Lesson[]> = {
  3: EN3, 4: EN4, 5: EN5, 6: EN6, 7: EN7,
  8: EN8, 9: EN9, 10: EN10, 11: EN11, 12: EN12,
};
